/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package heart_diaseasebrb;

import javax.swing.JOptionPane;

/**
 *
 * @author yasen al mamun
 */
public class diagonosis extends javax.swing.JFrame {
    String A="1";
     String B="2";
      double age;
    double secondNum;
    double tbps;
    double cho;
    double fifthNum;
    double sixthdNum;
    double thl;
    double eight;
    double old;
    double ten;
    double eleven;
    double prob1,proba2,probb3;
    double probability;
    double total;
    double Dn,Md,High,Medium,Low,Mn;
    
    /**
     * Creates new form diagonosis
     */
    public diagonosis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Age = new javax.swing.JComboBox();
        Bps = new javax.swing.JComboBox();
        Chol = new javax.swing.JComboBox();
        Thal = new javax.swing.JComboBox();
        cp = new javax.swing.JTextField();
        bps = new javax.swing.JTextField();
        chol = new javax.swing.JTextField();
        thal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        oldpeack = new javax.swing.JTextField();
        Oldpeack = new javax.swing.JComboBox();
        total1 = new javax.swing.JLabel();
        a1txt = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        prob = new javax.swing.JLabel();
        proba = new javax.swing.JLabel();
        probb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setText("A PREDICTIVE BELIEF RULE BASED EXPERT SYSTEM FOR HEART FAILURE ASSESSMENT");

        Age.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AGE", "20-30", "30-40", "40-60", " ", " " }));
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        Bps.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trestbps(Blood Pressure)", "1=point >=150", "0=point <150", " ", " " }));
        Bps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpsActionPerformed(evt);
            }
        });

        Chol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chol  (Serum Cholesterol)", "chol >= 275 1 pt", "chol < 275 0 pt", " ", " " }));
        Chol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CholActionPerformed(evt);
            }
        });

        Thal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thalach(maximum heart rate achieved )", "2.HR<=120", "1.HR(130 -150)", "0.HR>=150" }));
        Thal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThalActionPerformed(evt);
            }
        });

        jButton3.setText("Prediction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Oldpeack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oldpeak ", "0.ST>1", "1.ST >=1", "2. ST>=2", " ", " " }));
        Oldpeack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldpeackActionPerformed(evt);
            }
        });

        total1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total1.setText("Probability");

        prob.setText("Probability");

        proba.setText("Probability");

        probb.setText("Probability");

        jLabel1.setText("A1");

        jLabel2.setText("A2");

        jLabel3.setText("A3");

        jLabel4.setText("A4");

        jLabel5.setText("A5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Chol, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proba, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(probb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prob, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Oldpeack, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oldpeack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Thal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Bps, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bps, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(chol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(132, 132, 132)
                        .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prob)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proba)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(probb)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Oldpeack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldpeack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Data_set e = new Data_set();
        e.setVisible(true);
        hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
        String itemText = (String) Age.getSelectedItem();
        cp.setText(itemText);
          if(Age.getSelectedIndex()==1){
            cp.setText("0");
        }
        else if(Age.getSelectedIndex()==2){
            cp.setText("1");
        }
        else if(Age.getSelectedIndex()==3){
            cp.setText("2");
        }else if(Age.getSelectedIndex()==4){
            cp.setText("3");
        }
        else {
            cp.setText("");
        }
    }//GEN-LAST:event_AgeActionPerformed

    private void BpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpsActionPerformed
        // TODO add your handling code here:
        String itemText = (String) Bps.getSelectedItem();
        bps.setText(itemText);
          if(Bps.getSelectedIndex()==1){
            bps.setText("1");
        }
        else if(Bps.getSelectedIndex()==2){
            bps.setText("0");
        }
        else {
            bps.setText("");
        }
    }//GEN-LAST:event_BpsActionPerformed

    private void CholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CholActionPerformed
        // TODO add your handling code here:
        String itemText = (String) Chol.getSelectedItem();
        chol.setText(itemText);
        if(Chol.getSelectedIndex()==1){
            chol.setText("1");
        }
        else if(Chol.getSelectedIndex()==2){
            chol.setText("0");
        }
        else {
            chol.setText("");
        }
    }//GEN-LAST:event_CholActionPerformed

    private void ThalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThalActionPerformed
        // TODO add your handling code here:
        String itemText = (String) Thal.getSelectedItem();
        thal.setText(itemText);
         if(Thal.getSelectedIndex()==1){
            thal.setText("2");
        }
        else if(Thal.getSelectedIndex()==2){
            thal.setText("1");
        }
        else  {
            thal.setText("0");
        }
    }//GEN-LAST:event_ThalActionPerformed

    private void OldpeackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldpeackActionPerformed
        // TODO add your handling code here:
        String itemText = (String) Oldpeack.getSelectedItem();
        oldpeack.setText(itemText);
        if(Oldpeack.getSelectedIndex()==1){
            oldpeack.setText("1");
        }
       
         else if(Oldpeack.getSelectedIndex()==2){
            oldpeack.setText("1");
            
        }
          else if(Oldpeack.getSelectedIndex()==3){
            oldpeack.setText("2");
            
        }
        else  {
            oldpeack.setText("0");
        }
    }//GEN-LAST:event_OldpeackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        age = (Double.parseDouble(String.valueOf(cp.getText())));
        tbps = (Double.parseDouble(String.valueOf(bps.getText())));
        cho = (Double.parseDouble(String.valueOf(chol.getText())));
        
        thl = (Double.parseDouble(String.valueOf(thal.getText())));
        
        old = (Double.parseDouble(String.valueOf(oldpeack.getText())));
         total = age + tbps + cho + thl+old;
          Dn=Mn/(1-Md);
           High=Mn/(1-Md);
           Low=Mn/(1-Md);
           Medium=High-Low;
            if (age >= 2) {
            a1txt.setText("1");
        } else if (age == 1  ) {
            a1txt.setText("0.5");
        } else if (age >1 ) {
            a1txt.setText("0");
        }
                if (tbps >= 2) {
            jTextField2.setText("1");
        } else if (tbps == 1 ) {
            jTextField2.setText("0.5");
        } else if (tbps >1 ) {
            jTextField2.setText("0");
        }
                   if (cho >= 2) {
            jTextField3.setText("1");
        } else if (cho >= 1 ) {
            jTextField3.setText("0.5");
        } else if (cho >1 ) {
            jTextField3.setText("0");
        }
                   if (thl >=2) {
            jTextField4.setText("1");
        } else if (thl >= 1 ) {
            jTextField4.setText("0.5");
        } else if (thl >1 ) {
            jTextField4.setText("0");
        }
                   if (old >= 2) {
            jTextField5.setText("1");
        } else if (old >=1 ) {
            jTextField5.setText("0.5");
        } else if (old >1) {
            jTextField5.setText("0");
        }
                prob1=(1000*0.0841104)/total;
               proba2=(1000*0.0560736)/(age + tbps + cho + thl+old*10);
             probb3=100-(prob1+proba2);
             
           prob.setText(String.valueOf("High :"+prob1+"%"));
            proba.setText(String.valueOf("Low :"+proba2+"%"));
             probb.setText(String.valueOf("Medium :"+probb3+"%"));
        JOptionPane.showMessageDialog(null," Heart Diasease Probability Is:"
                + "\nHigh : "+prob1+"%"
                + "\nMedium : "+probb3+"%"
                + "\nLow :"+proba2+" %");
        
        total1.setText(String.valueOf((prob1*1)+(proba2*0.5)+(probb3*0+"%")));
       
//          
//            if (total >6) {
//
//            total1.setText(String.valueOf("HEART DISEASES"));
//            }
//            if (total <6) {
//
//            total1.setText(String.valueOf("NO HEART DISEASES"));
//            }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagonosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagonosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagonosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagonosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new diagonosis().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Age;
    private javax.swing.JComboBox Bps;
    private javax.swing.JComboBox Chol;
    private javax.swing.JComboBox Oldpeack;
    private javax.swing.JComboBox Thal;
    private javax.swing.JTextField a1txt;
    private javax.swing.JTextField bps;
    private javax.swing.JTextField chol;
    private javax.swing.JTextField cp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField oldpeack;
    private javax.swing.JLabel prob;
    private javax.swing.JLabel proba;
    private javax.swing.JLabel probb;
    private javax.swing.JTextField thal;
    private javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
